default_language_version:
  python: python3
exclude: ^docs/|/migrations/|Makefile|\.gitignore|poetry.lock

repos:

- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus, --keep-runtime-typing]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
    args: [--unsafe]
  - id: trailing-whitespace
    exclude: ^.*\.patch$
    args: [--markdown-linebreak-ext=md]
  - id: detect-private-key
  - id: pretty-format-json
  - id: check-added-large-files
  - id: check-json
  - id: check-symlinks
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-toml
  - id: mixed-line-ending
  - id: file-contents-sorter
    files: ^(\.env.*|\.gitignore|\.dockerignore)$
  - id: requirements-txt-fixer
    files: ^(requirements.*\.txt)$
  - id: end-of-file-fixer
    exclude: ^.*/VERSION$
  - id: fix-byte-order-marker
  - id: name-tests-test
    files: ^tests/(tests_integration|tests_unit)/.*\.py$
    args: [--django]
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: debug-statements

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-no-log-warn
  - id: python-no-eval
  - id: python-use-type-annotations
  - id: python-no-eval
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal
  - id: text-unicode-replacement-char

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: remove-tabs
    exclude: ^docs/(make.bat|Makefile)|tests/unit/example/.*$

- repo: https://github.com/PyCQA/autoflake
  rev: v2.3.1
  hooks:
  - id: autoflake

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.11
  hooks:
    - id: ruff-format
      exclude: ^.*\b(migrations)\b.*$
    - id: ruff
      args: [ --fix ]
