-   id: check-untracked-migrations
    name: Untracked Django migrations checker
    description: "Forbid untracked Django migrations"
    entry: check-untracked-migrations
    language: python
    always_run: true
    pass_filenames: false
